# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
a1,a2,a3

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape,a1.ndim,a1.dtype,a1.size,type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [7]:
# Attributes of 2-dimensional array
a2.shape,a2.ndim,a2.dtype,a2.size,type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [9]:
# Attributes of 3-dimensional array
a3.shape,a3.ndim,a3.dtype,a3.size,type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [11]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [14]:
# Create an array of shape (10, 2) with only ones
ones_array=np.ones((10,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array=np.zeros((7,2,3))
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
# Create an array within a range of 0 and 100 with step 3
step_array=np.arange(0,100,3)
step_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array=np.random.randint(0,10,size=(7,2))
random_array

array([[7, 2],
       [3, 9],
       [3, 5],
       [9, 7],
       [9, 9],
       [2, 9],
       [6, 3]])

In [23]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_2=np.random.rand(3,5)
random_array_2

array([[0.51689848, 0.4264851 , 0.90886994, 0.40218569, 0.27604065],
       [0.35225252, 0.36791478, 0.05344933, 0.84722278, 0.1336763 ],
       [0.00408984, 0.07172844, 0.00193673, 0.25086878, 0.51274973]])

In [26]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_3=np.random.rand(4,6)
random_array

array([[7, 2],
       [3, 9],
       [3, 5],
       [9, 7],
       [9, 9],
       [2, 9],
       [6, 3]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [30]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_4=np.random.randint(1,11,size=(3,7))
random_array_4
# Find the unique numbers in the array you just created
np.unique(random_array_4)

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

In [32]:
# Find the 0'th index of the latest array you created
random_array_4
random_array_4[0]

array([ 3,  1,  5, 10,  7, 10,  9])

In [37]:
# Get the first 2 rows of latest array you created
random_array_4[:2,:]

array([[ 3,  1,  5, 10,  7, 10,  9],
       [ 7,  9,  8,  2,  1,  7,  7]])

In [38]:
# Get the first 2 rows of latest array you created
random_array_4[:2,:]

array([[ 3,  1,  5, 10,  7, 10,  9],
       [ 7,  9,  8,  2,  1,  7,  7]])

In [39]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_4[:2,:2]

array([[3, 1],
       [7, 9]])

In [44]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
x_range=np.random.randint(0,10,size=(3,5))
x_ones=np.ones((3,5))
x_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
# Add the two arrays together
x_range+x_ones

array([[7., 9., 7., 1., 1.],
       [9., 9., 4., 9., 3.],
       [7., 6., 8., 9., 5.]])

In [48]:
# Create another array of ones of shape (5, 3)
y_ones=np.ones((5,3))
y_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
# Try add the array of ones and the other most recent array together
x_ones+y_ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [51]:
# Create another array of ones of shape (3, 5)
z_ones=np.ones((3,5))
z_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
# Subtract the new array of ones from the other most recent array
x_ones-z_ones

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
# Multiply the ones array with the latest array
x_ones*z_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
# Take the latest array to the power of 2 using '**'
np.random.seed(1)
sample_array=np.random.randint(0,10,size=(3,5))
sample_array**2

array([[25, 64, 81, 25,  0],
       [ 0,  1, 49, 36, 81],
       [ 4, 16, 25,  4, 16]], dtype=int32)

In [65]:
# Do the same thing with np.square()
np.square(sample_array)

array([[25, 64, 81, 25,  0],
       [ 0,  1, 49, 36, 81],
       [ 4, 16, 25,  4, 16]], dtype=int32)

In [66]:
# Find the mean of the latest array using np.mean()
np.mean(sample_array)

4.466666666666667

In [69]:
# Find the maximum of the latest array using np.max()
sample_array
np.max(sample_array)

9

In [70]:
# Find the minimum of the latest array using np.min()
np.min(sample_array)

0

In [71]:
# Find the standard deviation of the latest array
np.std(sample_array)

2.9181424837652385

In [72]:
# Find the variance of the latest array
np.var(sample_array)

8.515555555555556

In [73]:
# Reshape the latest array to (3, 5, 1)
sample_array

array([[5, 8, 9, 5, 0],
       [0, 1, 7, 6, 9],
       [2, 4, 5, 2, 4]])

In [74]:
# Transpose the latest array
sample_array.reshape(3,5,1)

array([[[5],
        [8],
        [9],
        [5],
        [0]],

       [[0],
        [1],
        [7],
        [6],
        [9]],

       [[2],
        [4],
        [5],
        [2],
        [4]]])

What does the transpose do?

In [76]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array1=np.random.randint(0,10,size=(3,3))
array2=np.random.randint(0,10,size=(3,2))

In [78]:
# Perform a dot product on the two newest arrays you create
result_array=array1.dot(array2)
result_array

array([[202, 120],
       [136,  93],
       [ 65,  32]])

In [79]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_1=np.random.randint(0,10,size=(4,3))
array_2=np.random.randint(0,10,size=(4,3))

In [80]:
# Perform a dot product on the two newest arrays you created
array1.dot(array_2)

ValueError: shapes (3,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [81]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
array_1.dot(array_2.T)

array([[ 16,  71,  95,  84],
       [ 34, 115, 122,  93],
       [ 32, 102,  97,  69],
       [ 36,  69,  99,  54]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [87]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
np.random.seed(0)
a1_check=np.random.randint(0,10,size=(2,3))
a2_check=np.random.randint(0,10,size=(2,3))
a1_check,a2_check

(array([[5, 0, 3],
        [3, 7, 9]]),
 array([[3, 5, 2],
        [4, 7, 6]]))

In [91]:
# Compare the two arrays with '>'
a1_check>a2_check

array([[ True, False,  True],
       [False, False,  True]])

What happens when you compare the arrays with `>`?

In [92]:
# Compare the two arrays with '>='
a1_check>=a2_check

array([[ True, False,  True],
       [False,  True,  True]])

In [93]:
# Find which elements of the first array are greater than 7
a1_check > 7

array([[False, False, False],
       [False, False,  True]])

In [94]:
# Which parts of each array are equal? (try using '==')
a1_check == a2_check

array([[False, False, False],
       [False,  True, False]])

In [98]:
# Sort one of the arrays you just created in ascending order
np.sort(a1_check)


array([[0, 3, 5],
       [3, 7, 9]])

In [100]:
# Sort the indexes of one of the arrays you just created
np.argsort(a1_check)

array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [105]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a1_check)
a1_check
np.argmax(a1_check)

5

In [107]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a1_check)
a1_check

array([[5, 0, 3],
       [3, 7, 9]])

In [108]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
np.argmax(a1_check,axis=0)

array([0, 1, 1], dtype=int64)

In [109]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.argmax(a1_check,axis=1)

array([0, 2], dtype=int64)

In [110]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[-0.05503512, -0.10731045,  1.36546718, -0.09769572, -2.42595457],
       [-0.4530558 , -0.470771  ,  0.973016  , -1.27814912,  1.43737068],
       [-0.07770457,  1.08963016,  0.09654267,  1.41866711,  1.16827314]])

In [111]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.